import frappe

@frappe.whitelist()
def loaddata():
    data= [
      {
        "name": "OPP252600001",
        "item_code": "Microsoft-Project-Plan3-1Month",
        "party_name": "ATMECS Technologies Pvt Ltd",
        "qty": 2,
        "amount": 4990,
        "forecast": "Include",
        "expected_date": "2025-04-02",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Software Subscriptions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 4022,
        "margin": 968,
        "orc": 0,
        "gross_profit": 968,
        "support": 96.8,
        "mdf": 96.8,
        "net_profit": 774.4,
        "item_row": "5dg3pk6gpg"
      },
      {
        "name": "OPP252600001",
        "item_code": "PowerBI-Pro-1Month",
        "party_name": "ATMECS Technologies Pvt Ltd",
        "qty": 1,
        "amount": 1165,
        "forecast": "Include",
        "expected_date": "2025-04-11",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Software Subscriptions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 996,
        "margin": 169,
        "orc": 0,
        "gross_profit": 169,
        "support": 16.9,
        "mdf": 16.9,
        "net_profit": 135.2,
        "item_row": "5dg3p1pitn"
      },
      {
        "name": "OPP252600002",
        "item_code": "M365-BB-1Yr",
        "party_name": "DWP GTS Private Limited",
        "qty": 155,
        "amount": 241800,
        "forecast": "Include",
        "expected_date": "2025-04-01",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 215760,
        "margin": 26040,
        "orc": 0,
        "gross_profit": 26040,
        "support": 2604,
        "mdf": 2604,
        "net_profit": 20832,
        "item_row": "5srji03e1q"
      },
      {
        "name": "OPP252600003",
        "item_code": "M365-BB-1Yr",
        "party_name": "Adepto Geoinformatics Private Ltd",
        "qty": 11,
        "amount": 16500,
        "forecast": "Include",
        "expected_date": "2025-04-03",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 14850,
        "margin": 1650,
        "orc": 0,
        "gross_profit": 1650,
        "support": 165,
        "mdf": 165,
        "net_profit": 1320,
        "item_row": "621upaenor"
      },
      {
        "name": "OPP252600004",
        "item_code": "Sophos-Intercept-X-EPAdv-3Yrs",
        "party_name": "INS Data Services Pvt Ltd",
        "qty": 80,
        "amount": 146800,
        "forecast": "Include",
        "expected_date": "2025-04-16",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Endpoint Protection",
        "brand": "Sophos",
        "territory": "Tamil Nadu",
        "buying_amount": 127600,
        "margin": 19200,
        "orc": 0,
        "gross_profit": 19200,
        "support": 1920,
        "mdf": 1920,
        "net_profit": 15360,
        "item_row": "6ff446i8uv"
      },
      {
        "name": "OPP252600005",
        "item_code": "M365-BB-1Yr",
        "party_name": "VINAY KUMAR PUVVALA",
        "qty": 5,
        "amount": 8000,
        "forecast": "Include",
        "expected_date": "2025-04-09",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Andhra Pradesh",
        "buying_amount": 6665,
        "margin": 1335,
        "orc": 0,
        "gross_profit": 1335,
        "support": 133.5,
        "mdf": 133.5,
        "net_profit": 1068,
        "item_row": "6ivjbvekb9"
      },
      {
        "name": "OPP252600006",
        "item_code": "M365-BB-1Yr",
        "party_name": "Sas Exports",
        "qty": 3,
        "amount": 4800,
        "forecast": "Include",
        "expected_date": "2025-04-11",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Lost",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Andhra Pradesh",
        "buying_amount": 0,
        "margin": 0,
        "orc": 0,
        "gross_profit": 0,
        "support": 0,
        "mdf": 0,
        "net_profit": 0,
        "item_row": "6prf5741ma"
      },
      {
        "name": "OPP252600007",
        "item_code": "M365-BB-1Yr",
        "party_name": "Supreme Netsoft Pvt Ltd",
        "qty": 2,
        "amount": 3200,
        "forecast": "Include",
        "expected_date": "2025-04-22",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Proposal",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 0,
        "margin": 0,
        "orc": 0,
        "gross_profit": 0,
        "support": 0,
        "mdf": 0,
        "net_profit": 0,
        "item_row": "6s2meesfar"
      },
      {
        "name": "OPP242501483",
        "item_code": "M365-BS-1Yr",
        "party_name": "P S V & ASSOCIATES",
        "qty": 1,
        "amount": 7500,
        "forecast": "Include",
        "expected_date": "2025-04-08",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 7100,
        "margin": 400,
        "orc": 0,
        "gross_profit": 400,
        "support": 40,
        "mdf": 40,
        "net_profit": 320,
        "item_row": "6v2hqoh3a3"
      },
      {
        "name": "OPP242501483",
        "item_code": "M365-BB-1Yr",
        "party_name": "P S V & ASSOCIATES",
        "qty": 5,
        "amount": 7500,
        "forecast": "Include",
        "expected_date": "2025-04-08",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 6750,
        "margin": 750,
        "orc": 0,
        "gross_profit": 750,
        "support": 75,
        "mdf": 75,
        "net_profit": 600,
        "item_row": "6v2hp15lva"
      },
      {
        "name": "OPP242501484",
        "item_code": "M365-AppsBusiness-1Yr",
        "party_name": "Hotel Avasa",
        "qty": 16,
        "amount": 98400,
        "forecast": "Include",
        "expected_date": "2025-04-14",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Software Subscriptions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 96000,
        "margin": 2400,
        "orc": 0,
        "gross_profit": 2400,
        "support": 240,
        "mdf": 240,
        "net_profit": 1920,
        "item_row": "7lej8b87o7"
      },
      {
        "name": "OPP242501485",
        "item_code": "M365-BB-1Yr",
        "party_name": "Voidpeak Games Pvt Ltd",
        "qty": 5,
        "amount": 7250,
        "forecast": "Include",
        "expected_date": "2025-04-12",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 6665,
        "margin": 585,
        "orc": 0,
        "gross_profit": 585,
        "support": 58.5,
        "mdf": 58.5,
        "net_profit": 468,
        "item_row": "7oil46n3ja"
      },
      {
        "name": "OPP242501486",
        "item_code": "M365-BB-1Yr",
        "party_name": "Scientific Erevna Private Limited",
        "qty": 16,
        "amount": 24960,
        "forecast": "Include",
        "expected_date": "2025-04-09",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 21328,
        "margin": 3632,
        "orc": 0,
        "gross_profit": 3632,
        "support": 363.2,
        "mdf": 363.2,
        "net_profit": 2905.6,
        "item_row": "9bs2eatab1"
      },
      {
        "name": "OPP252600008",
        "item_code": "Trellix-Std-1YR",
        "party_name": "Convosight Analytics Private Limited",
        "qty": 65,
        "amount": 106600,
        "forecast": "Include",
        "expected_date": "2025-04-11",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Endpoint Protection",
        "brand": "Trellix",
        "territory": "Haryana",
        "buying_amount": 76095.5,
        "margin": 30504.5,
        "orc": 0,
        "gross_profit": 30504.5,
        "support": 3050.45,
        "mdf": 3050.45,
        "net_profit": 24403.6,
        "item_row": "bpk4cp3u47"
      },
      {
        "name": "OPP252600009",
        "item_code": "Cyber Security as a Service - 1 Month",
        "party_name": "Vasant Chemicals Pvt Ltd",
        "qty": 1,
        "amount": 145917,
        "forecast": "Include",
        "expected_date": "2025-04-01",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Services",
        "brand": "eScan",
        "territory": "Telangana",
        "buying_amount": 0,
        "margin": 0,
        "orc": 0,
        "gross_profit": 0,
        "support": 0,
        "mdf": 0,
        "net_profit": 0,
        "item_row": "cnrquf8093"
      },
      {
        "name": "OPP252600010",
        "item_code": "AutoCAD-LT2025-Comm-SingleUser Renewal -1Yr",
        "party_name": "Indus Projects Pvt.Ltd",
        "qty": 5,
        "amount": 131250,
        "forecast": "Include",
        "expected_date": "2025-04-09",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Software Subscriptions",
        "brand": "Autodesk",
        "territory": "Telangana",
        "buying_amount": 128250,
        "margin": 3000,
        "orc": 0,
        "gross_profit": 3000,
        "support": 300,
        "mdf": 300,
        "net_profit": 2400,
        "item_row": "vol2jjn9p0"
      },
      {
        "name": "OPP252600011",
        "item_code": "M365-BB-1Yr",
        "party_name": "Indus Projects Pvt.Ltd",
        "qty": 3,
        "amount": 1770,
        "forecast": "Include",
        "expected_date": "2025-04-09",
        "committed_date": "null",
        "opportunity_type": "Additional",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 1665,
        "margin": 105,
        "orc": 0,
        "gross_profit": 105,
        "support": 10.5,
        "mdf": 10.5,
        "net_profit": 84,
        "item_row": "04veapouln"
      },
      {
        "name": "OPP252600012",
        "item_code": "KAS-Select-3Yrs",
        "party_name": "Meenakshi Infrastrusture Pvt Ltd",
        "qty": 80,
        "amount": 116000,
        "forecast": "Include",
        "expected_date": "2025-04-29",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Proposal",
        "item_group": "Endpoint Protection",
        "brand": "Kaspersky",
        "territory": "Telangana",
        "buying_amount": 0,
        "margin": 0,
        "orc": 0,
        "gross_profit": 0,
        "support": 0,
        "mdf": 0,
        "net_profit": 0,
        "item_row": "0pga6g68rg"
      },
      {
        "name": "OPP252600012",
        "item_code": "KAS-NEXT EDRO-1Yr",
        "party_name": "Meenakshi Infrastrusture Pvt Ltd",
        "qty": 80,
        "amount": 88000,
        "forecast": "Exclude",
        "expected_date": "2025-04-29",
        "committed_date": "null",
        "opportunity_type": "New",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Proposal",
        "item_group": "Endpoint Protection",
        "brand": "Kaspersky",
        "territory": "Telangana",
        "buying_amount": 0,
        "margin": 0,
        "orc": 0,
        "gross_profit": 0,
        "support": 0,
        "mdf": 0,
        "net_profit": 0,
        "item_row": "l0uv96kv23"
      },
      {
        "name": "OPP252600012",
        "item_code": "KAS-Next-EDR-Optimum-3Yrs",
        "party_name": "Meenakshi Infrastrusture Pvt Ltd",
        "qty": 80,
        "amount": 172000,
        "forecast": "Exclude",
        "expected_date": "2025-04-29",
        "committed_date": "null",
        "opportunity_type": "New",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Proposal",
        "item_group": "Endpoint Protection",
        "brand": "Kaspersky",
        "territory": "Telangana",
        "buying_amount": 0,
        "margin": 0,
        "orc": 0,
        "gross_profit": 0,
        "support": 0,
        "mdf": 0,
        "net_profit": 0,
        "item_row": "hu7js7s2as"
      },
      {
        "name": "OPP252600013",
        "item_code": "KAS-Select-1Yr",
        "party_name": "Andhra Pradesh State Financial Corporation(Andhra Division)",
        "qty": 184,
        "amount": 80960,
        "forecast": "Include",
        "expected_date": "2025-04-21",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Endpoint Protection",
        "brand": "Kaspersky",
        "territory": "Andhra Pradesh",
        "buying_amount": 57040,
        "margin": 23920,
        "orc": 8004,
        "gross_profit": 15916,
        "support": 1591.6,
        "mdf": 1591.6,
        "net_profit": 12732.8,
        "item_row": "0v1mdk3f1g"
      },
      {
        "name": "OPP252600014",
        "item_code": "M365-BB-1Yr",
        "party_name": "Nuhainternational",
        "qty": 5,
        "amount": 8000,
        "forecast": "Include",
        "expected_date": "2025-04-02",
        "committed_date": "null",
        "opportunity_type": "New",
        "sales_person": "Salman Naved Mohammed",
        "sales_stage": "Closed Won",
        "item_group": "Email Solutions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 6480,
        "margin": 1520,
        "orc": 0,
        "gross_profit": 1520,
        "support": 152,
        "mdf": 152,
        "net_profit": 1216,
        "item_row": "1aldh6udkh"
      },
      {
        "name": "OPP252600015",
        "item_code": "AutoCAD-LT2025-Comm-SingleUser Renewal -1Yr",
        "party_name": "Vasant Chemicals Pvt Ltd",
        "qty": 2,
        "amount": 52300,
        "forecast": "Include",
        "expected_date": "2025-04-15",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Software Subscriptions",
        "brand": "Autodesk",
        "territory": "Telangana",
        "buying_amount": 51300,
        "margin": 1000,
        "orc": 0,
        "gross_profit": 1000,
        "support": 100,
        "mdf": 100,
        "net_profit": 800,
        "item_row": "1errgrrku8"
      },
      {
        "name": "OPP252600016",
        "item_code": "Microsoft-Project-Plan1-1Yr",
        "party_name": "Rajapushpa Properties Pvt Ltd",
        "qty": 1,
        "amount": 9960,
        "forecast": "Include",
        "expected_date": "2025-04-04",
        "committed_date": "null",
        "opportunity_type": "New",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Software Subscriptions",
        "brand": "Microsoft",
        "territory": "Telangana",
        "buying_amount": 7750,
        "margin": 2210,
        "orc": 0,
        "gross_profit": 2210,
        "support": 221,
        "mdf": 221,
        "net_profit": 1768,
        "item_row": "4qah2s5rq8"
      },
      {
        "name": "OPP252600017",
        "item_code": "Google-WS-Starter-1Yr",
        "party_name": "Furniture World",
        "qty": 5,
        "amount": 16200,
        "forecast": "Include",
        "expected_date": "2025-04-18",
        "committed_date": "null",
        "opportunity_type": "Renewal",
        "sales_person": "Geetha Pudi",
        "sales_stage": "Closed Won",
        "item_group": "Email Solutions",
        "brand": "Google",
        "territory": "Telangana",
        "buying_amount": 14220,
        "margin": 1980,
        "orc": 0,
        "gross_profit": 1980,
        "support": 198,
        "mdf": 198,
        "net_profit": 1584,
        "item_row": "4updbqnvtp"
      }]
    return data